const weatherCodeAndIcons: { [key: number]: string } = {
  0: "☀️",
  1: "🌤️",
  2: "⛅",
  3: "☁️",
  45: "🌫️",
  48: "🌁",
  51: "🌦️",
  53: "🌦️",
  55: "🌧️",
  56: "🌧",
  57: "🌧",
  61: "🌦️",
  63: "🌧️",
  65: "🌧",
  66: "🌧",
  67: "🌧",
  71: "🌨️",
  73: "🌨️",
  75: "❄️",
  77: "❄️",
  80: "🌦️",
  81: "🌧️",
  82: "🌧",
  85: "🌨️",
  86: "🌨",
  95: "⛈️",
  96: "⛈️",
  99: "⛈️",
};

const weatherCodeTitles: { [key: number]: string } = {
  0: "Sunny",
  1: "Mainly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Foggy",
  48: "Depositing Rime Fog",
  51: "Light Drizzle",
  53: "Moderate Drizzle",
  55: "Dense Drizzle",
  56: "Light Freezing Drizzle",
  57: "Dense Freezing Drizzle",
  61: "Slight Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  66: "Light Freezing Rain",
  67: "Heavy Freezing Rain",
  71: "Slight Snowfall",
  73: "Moderate Snowfall",
  75: "Heavy Snowfall",
  77: "Snow Grains",
  80: "Slight Rain Showers",
  81: "Moderate Rain Showers",
  82: "Violent Rain Showers",
  85: "Slight Snow Showers",
  86: "Heavy Snow Showers",
  95: "Thunderstorm",
  96: "Thunderstorm",
  99: "Thunderstorm",
};

export const getWeatherTitleIcon = (weathercode: number) => {
  const icon = weatherCodeAndIcons[weathercode] || "❓";
  const title = weatherCodeTitles[weathercode] || "Unknown";
  return { title, icon };
};
